language: java
jdk:
  - oraclejdk8

script:
  - ./gradlew test jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - .utility/push_javadocs.sh
  - .utility/publish.sh

env:
  global:
    secure: "AZgJDtqOn42+s9ku+S4ObMLDw7NCpg1AJqpJhEKahji1xvxexjWnYKUj3Kpo85CipnsNbOa2U5GuCd5CLVauQ02ZaXnSIePUu5yVnk1oBUb0fCEG3FvGMvpKuotl9XlUqMfZv1OFhTDqtszPwso3pCnnKV1c0j6kecm44q5ICZ7VrT/tDYX74JZ9N4SPkanVomf/r1ow6r0OGt7FeFsSDRCJ8L1QTMPo4UJRTK1eboJSEo8tq4uZ8yX0mX9MYupxvKzs9EYIBICiis55Z/M9RXxoY7EIljX6Vwk2dO/LYv406kO+zzy+vTmnNsqRDj78kPKFoARdZxAWKyUH+pHdGwi6qy1pVzCJSU1c/sIXg+jHp+5GjdeG4eHdOFrZoRPxeIXYqB3EfRrbaBfL1nNcdWxnypbx5dPVJA2aI9OtU7Abz3rxiwRTbt6GETe3eCqL+BRvvXOkDZR1pzGGt76X9MdCWsBzJ419Wnza9Dy8ujeiG25WQ2mlWn2ELS6ZP72MgjUYVqa82pDdx/X6Tu74knvUPEDKxaZrPnHBM/2vxSUiGgU+Ix96skAYOoMmTuILnB0l6T59I7XSSrhUz6tEmAZegxrERNIxsCyM4q6UqnKWdaeB2LrKYc2kNJdEbopHgiLLAbgYkv5j6zByJ8OTzRM4D1lYFSjllR4t7sc+lFs="
