language: java
jdk:
  - oraclejdk8

script:
  - ./gradlew test jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: "aBdvRk5u50t3bzCvpvZcFoqFzBq68hLp/r12J1XL2pm+VhyA+ncn3ayEb5r1DB+ow6WZWtyO0MeSwyxPbJ8AlVEz9B+K00kTiXtAz5hiqn4kGyETkg5u8tK7ced8urNHKmMjuUo8nS2kDuTjRJ/o+c2Dj1GnDKQUf1zKuAAp1bWCgvnnJaT2SiGNErs285surVDzUYa5lRjuMH2WN7/ftkR1LCjE6VqnlhjuhRXUSArEvUumTvnMVw903atI3slvO8wbT4gB7JBC9OBUBYWdsWLh44/exALSFl41uPLA+GUdf0qmYT4add5FiR0lFTSerziVsh6OhNY0qA9/g6GgR/B+hw/QpG4eJ1eEAcriySKo+QUdN7xP1Bc5RI+jnXsHo9j+a12w1CQ3BzhSQ7S+INXgUSkU6WJz1dIVBNCicZP5MhUHjIq3I3wizCU+wMLOTnSIS9zxt93NtnFtLM3MZ26yg9ZWiA0s99QGBtM2EcjDTuXyJ4U86Pcsfl30LOsf313iC22vRw5j30qufZ9OKawH123ArAPHBr9UD1fTsivSkyDZNqxppzBN6UB7NpYae+cJa4AqDR5q3y0a/ZwfdIc3SiIdEqOx0y7Ut5PmDD6oXFkRk9eGW9ZTL1rkdZbs3I2ed4tAw3VvawlvcfWgMWFoF09uu5DXQYK6397u0pQ="